# Generated by Django 2.0.2 on 2019-01-06 14:24

import customer.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fax', models.IntegerField(blank=True, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, default=customer.models.default_customer_code, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date2', django_jalali.db.models.jDateField(default=django.utils.timezone.now)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('fax', models.CharField(blank=True, max_length=15, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=15, null=True)),
                ('addr', models.TextField(blank=True, max_length=600, null=True)),
                ('agent', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('read_customer', 'Can read a customer details'), ('index_customer', 'Can see list of customers')),
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.Type'),
        ),
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
    ]
