# Generated by Django 2.0.2 on 2019-02-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReqEntered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_entered', models.CharField(blank=True, max_length=20, null=True)),
                ('number_automation', models.IntegerField(unique=True)),
                ('is_entered', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('owner_text', models.CharField(default='الوند', max_length=40)),
                ('date_txt', models.CharField(blank=True, max_length=12, null=True)),
                ('customer', models.CharField(blank=True, max_length=200, null=True)),
                ('is_request', models.BooleanField(default=True)),
                ('attachment', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=600, null=True)),
            ],
        ),
    ]
