# Generated by Django 2.0.2 on 2018-12-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('kw', models.IntegerField(blank=True, choices=[(0, '5.5 kw'), (1, '7.5 kw'), (2, '11 kw'), (3, '15 kw'), (4, '18.5 kw'), (5, '22 kw'), (6, '30 kw'), (7, '37 kw'), (8, '45 kw'), (9, '55 kw'), (10, '75 kw'), (11, '90 kw'), (12, '110 kw'), (13, '132 kw'), (14, '160 kw'), (15, '185 kw'), (16, '200 kw'), (17, '220 kw'), (18, '250 kw'), (19, '280 kw'), (20, '315 kw'), (21, '355 kw'), (22, '400 kw'), (23, '450 kw'), (24, '500 kw'), (25, '560 kw'), (26, '630 kw'), (27, '710 kw'), (28, '800 kw'), (29, '900 kw'), (30, '1000 kw'), (31, '1120 kw'), (32, '1250 kw'), (33, '1400 kw'), (34, '1600 kw'), (35, '1800 kw'), (36, '2000 kw')], default=7, null=True)),
                ('frame_size', models.CharField(max_length=6)),
                ('speed', models.IntegerField(blank=True, choices=[(3, '750 RPM'), (0, '1000 RPM'), (1, '1500 RPM'), (2, '3000 RPM')], default=1, null=True)),
                ('voltage', models.IntegerField(blank=True, choices=[(0, '380'), (1, '400'), (2, '3000'), (3, '3300'), (4, '6000'), (5, '6600')], default=0, null=True)),
                ('ip', models.IntegerField(blank=True, choices=[(0, 'IP55'), (1, 'IP65'), (2, 'IP23'), (3, 'Other')], default=0, null=True)),
                ('ic', models.IntegerField(blank=True, choices=[(0, 'IC411'), (1, 'IC511'), (2, 'IC611')], default=0, null=True)),
                ('ex_type', models.IntegerField(choices=[(0, 'safe'), (1, 'Exn'), (2, 'ExnA'), (3, 'Exe'), (4, 'Exd'), (5, 'Exde'), (6, 'other types')], default=0)),
                ('efficiency', models.FloatField()),
                ('PF', models.FloatField()),
                ('current_ln', models.FloatField()),
                ('current_ls_to_ln', models.FloatField()),
                ('torque_tn', models.FloatField()),
                ('torque_ts_to_tn', models.FloatField()),
                ('torque_tmax_to_tn', models.FloatField()),
                ('torque_rotor_inertia', models.FloatField()),
                ('weight', models.FloatField()),
                ('freq', models.FloatField(default=50)),
                ('im', models.IntegerField(choices=[(0, 'IMB3'), (1, 'IMB35')], default=0)),
                ('summary', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'permissions': (('view_motordb', 'can view motor database'), ('index_motordb', 'can view list of motor database')),
            },
        ),
    ]
