# Generated by Django 2.0.2 on 2019-01-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motordb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorsCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kw', models.DecimalField(decimal_places=1, max_digits=7)),
                ('frame_size', models.CharField(max_length=6)),
                ('speed', models.IntegerField()),
                ('voltage', models.IntegerField()),
                ('ip', models.IntegerField()),
                ('ic', models.IntegerField()),
                ('efficiency', models.FloatField()),
                ('PF', models.FloatField()),
                ('current_ln', models.FloatField()),
                ('current_ls_to_ln', models.FloatField()),
                ('torque_tn', models.FloatField()),
                ('torque_ts_to_tn', models.FloatField()),
                ('torque_tmax_to_tn', models.FloatField()),
                ('torque_rotor_inertia', models.FloatField()),
                ('weight', models.FloatField()),
                ('freq', models.FloatField(default=50)),
                ('im', models.CharField(max_length=8)),
                ('summary', models.TextField(blank=True, max_length=700, null=True)),
            ],
        ),
    ]
