# Generated by Django 2.0.2 on 2019-01-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motordb', '0002_motorscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorscode',
            name='code',
            field=models.CharField(default=0, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
