# Generated by Django 2.0.2 on 2019-01-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motordb', '0003_motorscode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorscode',
            name='PF',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motorscode',
            name='current_ln',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motorscode',
            name='current_ls_to_ln',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motorscode',
            name='efficiency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motorscode',
            name='ic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motorscode',
            name='im',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='motorscode',
            name='ip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motorscode',
            name='torque_rotor_inertia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motorscode',
            name='torque_tmax_to_tn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motorscode',
            name='torque_tn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motorscode',
            name='torque_ts_to_tn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motorscode',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
