# Generated by Django 2.0.2 on 2019-01-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motordb', '0004_auto_20190127_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motorscode',
            old_name='PF',
            new_name='pf',
        ),
        migrations.AddField(
            model_name='motorscode',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='motorscode',
            name='yd',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
