# Generated by Django 2.0.2 on 2019-01-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motordb', '0005_auto_20190127_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorscode',
            name='voltage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
