# Generated by Django 2.0.2 on 2019-01-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motordb', '0006_auto_20190127_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorscode',
            name='yd',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
