# Generated by Django 2.0.2 on 2019-01-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motordb', '0007_auto_20190127_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorscode',
            name='frame_size',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
