# Generated by Django 2.0.2 on 2019-01-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='number',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
