# Generated by Django 2.0.2 on 2019-01-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20190117_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='added_by_customer',
            field=models.BooleanField(default=False),
        ),
    ]
