# Generated by Django 2.0.2 on 2019-01-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_requests_added_by_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='edited_by_customer',
            field=models.BooleanField(default=False),
        ),
    ]
