# Generated by Django 2.0.2 on 2019-01-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_requests_edited_by_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
