# Generated by Django 2.0.2 on 2019-01-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_auto_20190120_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='parent_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
