# Generated by Django 2.0.2 on 2019-02-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_auto_20190202_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='temp_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
