# Generated by Django 2.0.2 on 2019-02-12 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_requests_temp_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='temp_number',
        ),
    ]
