# Generated by Django 2.0.2 on 2019-02-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_remove_requests_temp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='temp_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
