# Generated by Django 2.0.2 on 2019-02-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_requests_temp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpref',
            name='temp_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
