# Generated by Django 2.0.2 on 2019-02-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0012_payment_temp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='temp_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='temp_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='xpref',
            name='temp_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
