# Generated by Django 2.0.2 on 2019-02-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0013_auto_20190212_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
