# Generated by Django 2.0.2 on 2019-02-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0014_requests_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqspec',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
