# Generated by Django 2.0.2 on 2019-02-16 13:35

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0015_reqspec_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='date_finished',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
