# Generated by Django 2.0.2 on 2019-02-27 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0016_requests_date_finished'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prefspec',
            options={'permissions': (('index_prefspecs', 'can see list of prefspecs'),)},
        ),
    ]
